[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
allow-dirty = ["ci"]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.27.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "aarch64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-gnu",
]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
pr-run-mode = "upload"
github-attestations = true

# Force disable the containerised runner for aarch64-pc-windows-msvc
# as it makes it a snowflake.
[dist.github-custom-runners.aarch64-pc-windows-msvc]
runner = "windows-11-arm"

# Remove ubuntu-20.04
[dist.github-custom-runners.x86_64-unknown-linux-musl]
runner = "ubuntu-latest"
[dist.github-custom-runners.aarch64-unknown-linux-gnu]
runner = "ubuntu-latest"
[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-latest"
