name: Continuous Integration

on:
  pull_request:
    branches: [master]

# Release already exercises a build, so this only needs to worry about testable targets

jobs:
  verify:
    strategy:
      matrix:
        runner:
          - ubuntu-latest   # x86_64-unknown-linux-gnu
          - macos-13        # x86_64-apple-darwin
          - macos-latest    # aarch64-apple-darwin
          - windows-latest  # x86_64-pc-windows-msvc
    name: Verify (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          key: ${{ matrix.runner }}
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Test
        run: cargo test --all-targets --all-features

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
      - name: Format
        run: cargo fmt --all -- --check
